<?php

namespace AppBundle\Repository;

/**
 * classListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class classListRepository extends \Doctrine\ORM\EntityRepository
{
}
