<?php

namespace AppBundle\Repository;

/**
 * planRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class planRepository extends \Doctrine\ORM\EntityRepository
{
}
